FROM node:16-alpine

WORKDIR "/app"


COPY package.json .

RUN npm install

# we dont need the following since we're using volumes, but we're leaving it if we stop using volumes
COPY . .

CMD [ "npm", "run", "start" ]