name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker image
      run: docker build -t tolaat/docker-react -f Dockerfile.dev .

    - name: Run Docker container
      run: docker run -e CI=true tolaat/docker-react npm run test

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-west-2

    - name: Upload to S3
      run: aws s3 cp deploy.zip s3://elasticbeanstalk-us-west-2-160569206162/deploy.zip

    - name: Deploy to Elastic Beanstalk
      run: |
        VERSION_LABEL=$(date +%Y%m%d%H%M%S)
        
        aws elasticbeanstalk create-application-version \
          --application-name frontend \
          --version-label $VERSION_LABEL \
          --source-bundle S3Bucket=elasticbeanstalk-us-west-2-160569206162,S3Key=deploy.zip
          
        aws elasticbeanstalk update-environment \
          --application-name frontend \
          --environment-name Frontend-env \
          --version-label $VERSION_LABEL
